[project]
name = "3dprinting-shenanigans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "ruff>=0.12.4",
    "scikit-image>=0.25.2",
    "trimesh>=4.7.1",
]
